---

openshift_install_dir: "{{ playbook_dir }}/../{{ cluster_name }}"
ssh_public_key_location: /root/.ssh/id_rsa

vn_subnet: "192.168.50.0"
vn_name: "openshift-4-cluster"
vn_internal_domain: "compute.local"
vn_public_domain: "h42.openshift.pub"

listen_address: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"

master_count: 3
master_vcpu: 4
master_memory_size: 16384
master_memory_unit: 'MiB'
# qemu-img image size specified.
#   You may use k, M, G, T, P or E suffixe
master_root_disk_size: '120G'

compute_count: 3
compute_vcpu: 2
compute_memory_size: 8192
compute_memory_unit: 'MiB'
# qemu-img image size specified.
#   You may use k, M, G, T, P or E suffixe
compute_root_disk_size: '120G'

# Important: OpenShift version must match to RHEL CoreOS version!

# reference to OpenShift version
openshift_version: 4.2.0-0.nightly-2019-09-24-194016

# reference to coreos qcow file
coreos_version: 42.80.20190828.2
coreos_image_location: /var/lib/libvirt/images/rhcos-{{ coreos_version }}-qemu.qcow2 


certificates_dir: "{{ playbook_dir }}/../certificate"
certficate_fullchain: "{{ certificates_dir }}/{{ cluster_name }}.{{ public_domain }}/fullchain.crt"
certficate_key: "{{ certificates_dir }}/{{ cluster_name }}.{{ public_domain }}/cert.key"

# NFS Storage
#  storage_nfs do not support multi cluster support, it overwrites the
#  /etc/exports  
storage_nfs: false
storage_nfs_path_prefix: '/var/lib/libvirt/images'
storage_nfs_target_namespace: openshift-nfs-provisioner

install_ocs: true
